services:
  postgres:
    image: postgres:latest
    container_name: productsapi
    restart: always
    environment:
      POSTGRES_DB: productsapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: